### ISSUE TITLE
support for licence query?

### ISSUE THREAD

**Issue by baywet** [MastaBaba/LoremFlickr-2#1]
Nice solution!
Most of the images on Flickr are licensed, it'd be nice to be able to pass a license query to be able to filter out the images we can't display in some contexts.

**Comment by MastaBaba** [comment]
Thanks. Yeah, I've had that in the back of my mind for a while. 

I *am* considering a service that lets you put in more requirements for the returned images. However, this then quickly becomes pretty much the same as Flickr's own API.

That said, watch this space.
