### ISSUE TITLE
retrieving image URL via API

### ISSUE THREAD

**Issue by norcross** [MastaBaba/LoremFlickr-2#2]
Is there a way to retrieve the actual image filename that can be used? I'm creating a WordPress plugin that generates test data and I'd like to use this image API if I can, but I would need the actual URL.

example: doing a GET request to `https://loremflickr.com/600/600` would return a JSON array of data which would include the `https://loremflickr.com/cache/resized/4105_5037255879_a514fdbcfa_b_600_600_nofilter.jpg` image URL itself.

For the record, I am not intending on hotlinking images, rather, importing them into the WP database.

**Comment by MastaBaba** [comment]
Currently not available. Wouldn't be hard to build, but is also the kind of functionality that might as well be picked up straight from the Flickr API.

Buuuuut... is it really practical to use LoremFlickr? Cache gets regularly cleaned, so you might store the URL in your database, but by the time you want to use the URL, the file might be gone.

**Comment by norcross** [comment]
to clarify: the actual image is stored as though the user uploaded it themselves.

**Comment by MastaBaba** [comment]
Ah. But then, wouldn't you just be able to pick up the file to which the requested URL redirects to?

**Comment by norcross** [comment]
that’s where i’m struggling. it’s giving me the actual stream data of the image, which PHP can choke on sometimes and also can get mangled in various escaping / sanitizing functions. 

a _really_ simple thing would be just adding a parameter that just returns a raw text URL

**Comment by MastaBaba** [comment]
Ok. Give me a few days. I've put this on my to do list.

**Comment by norcross** [comment]
you’re a gentleman and a scholar.

**Comment by MastaBaba** [comment]
Your words are too kind.

Try this and let me know if it works for you:

https://loremflickr.com/json/g/320/240/paris,girl/all

**Comment by norcross** [comment]
this is *perfect* and exactly what i'm looking for. How are the various parameters passed now?

**Comment by MastaBaba** [comment]
It should be exactly the same as getting a regular image, except that you start with /json/. 

So, your example of `https://loremflickr.com/json/g/600/600/all` should actually return a 'greened' image of 600x600 pixels matching the keyword `all`.

Try this for a completely random image (of a cat):

`https://loremflickr.com/json/600/600`

**Comment by norcross** [comment]
fantastic. thank you so very much.
