### ISSUE TITLE
Cors headers

### ISSUE THREAD

**Issue by jnordberg** [MastaBaba/LoremFlickr-2#4]
First of all thanks for this amazingly useful service!

It would be useful if it also had permissive CORS headers for the images served, that way they can be used in applications that want to read the pixel data of images

**Comment by MastaBaba** [comment]
Glad you enjoy the service.

I don't think I follow your request. CORS is already turned on. 
What, specifically, would need to change, and to make sure your request wouldn't break Flickr requirements, what do you exactly want to do?

**Comment by jnordberg** [comment]
Images are not served with any CORS headers as far as I can tell. I want to put them in a `<img>` tag with `crossorigin="anonymous"` and read the pixel data with a html canvas.

They would need:
```
Access-Control-Allow-Origin: *
```

**Comment by MastaBaba** [comment]
Only seeing your response now. Will investigate and get back to you.

**Comment by MastaBaba** [comment]
Could you check again?

**Comment by jnordberg** [comment]
Nope, still not working. I think the redirect needs CORS headers as well

**Comment by MastaBaba** [comment]
Added. Let me know if it works.

**Comment by rbroth** [comment]
I've just started having problems related to this. It was working fine at the beginning of November, but now I'm getting the following error: 
```
"Access to image at 'https://loremflickr.com/cache/resized/65535_50642556191_e19d1497f0_b_800_600_nofilter.jpg' (redirected from 'https://loremflickr.com/800/600/geological?random=0.8405022925044905') from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: http://localhost/help (0
```

Maybe it has to do with the server migration?
It could also just be a problem on my end.

Also, thank you for the service

**Comment by MastaBaba** [comment]
Thanks @rbroth. I'm unable to reproduce this. Are you experiencing this only on your localhost?

**Comment by rbroth** [comment]
Sorry, I forgot to mention that this is inside an ionic cordova javascript android app that I'm working on. I'm currently running the app in an emulator. Other people on my team are experiencing the same problem. I'll ask one of us to try it on a phyiscal device.

**Comment by MastaBaba** [comment]
Thanks for the explainer. I think you might have encountered something that was a consequence of the server move. CORS should now be correctly set up.
Can you confirm?

**Comment by rbroth** [comment]
I can confirm that everything works now and that I am no longer getting CORS errors. Thank you very much for the quick fix :)

**Comment by MastaBaba** [comment]
My pleasure. Thanks for letting me know :)
